### ISSUE TITLE
Support Canner Enterprise's PAT authentication in VulcanSQL 

### ISSUE THREAD

**Issue by onlyjackfrost** [Canner/vulcan-sql#177]
## What’s the problem you're trying to solve
Support Canner Enterprise's PAT Authentication method

## Describe the solution you’d like
Add a extension authenticator "CannerPATAuthenticator" to restrict only users of Canner Enterprise could access VulcanSQL API

YAML example:
``` yaml
extensions:
  authenticator-canner: @vulcan/module_path

auth:
  enabled: true

authenticator-canner:
  options:
    canner-pat:
        host: string
        port: number
        ssl: boolean
```

The CannerPATAuthenticator will recognize whether a token is a PAT token with the prefix "Canner-PAT"(case-insensitive) in the authorization header / payload / query string
eg: 
```
Authorization: "Canner-PAT your_canner_pat_token"
```
