### ISSUE TITLE
Update Documentation(duckdb as cache)

### ISSUE THREAD

**Issue by cyyeh** [Canner/vulcan-sql#210]
## What’s the problem you're trying to solve

Add documentation on how to setup cache

## Describe the solution you’d like

We also need to add cache in `vulcan.yaml`

```
# vulcan.yaml
...

cache:
  type: parquet
  folderPath: tmp
  loader: duckdb
 ```
 
reference: https://github.com/Canner/vulcan-sql/pull/162

## Additional context

None
