### ISSUE TITLE
refreshExpression does not send a SQL request to the backend DB at the specified intervals

### ISSUE THREAD

**Issue by NithinKumaraNT** [Canner/vulcan-sql#370]
## Environment

- Version:
  v0.10.4

- OS: macOS - x86

## What's wrong?

The `refreshExpression` seems to not function. It does not invalidate the cache and refresh it based on the SQL expression.
Backend DB : BigQuery

The following is the example YAML config :
```YAML
....

sql: |
      SELECT
        *
      FROM
        mytable
    profile: bq
    refreshExpression:
        expression: "MAX(_processed_at)"
        every: "30s"

```

Please note that just using the `refreshTime` works without problems.

## What's the correct behavior?

A SQL request should be sent every 30 s based on the above config to BigQuery to check and invalidate the cache.
