### ISSUE TITLE
The server returns json format for requests with `.csv` file extension

### ISSUE THREAD

**Issue by oscar60310** [Canner/vulcan-sql#45]
## Environment
dev

## What's wrong?
The server always returns data in JSON format even if we send the requests env with `.csv`. e.g. http://localhost:3000/api/artist/1/works.csv

## What's the correct behavior?
It should returns csv format.

## Reproducing steps
1. Start server with playground
2. curl http://localhost:3000/api/artist/1/works.csv

**Comment by kokokuo** [comment]
Hi @oscar60310, thanks for replying to the issue, I'm curious have you set the `response-format` options first when you call `http://localhost:3000/api/artist/1/works.csv` ?

If you have not setup the `response-format` options first, and not provide `formats` or change the `default` to 'csv', even you pass the `work.csv`, it only work for json.

below is an `reponse-format` config explanataion:

```yaml
response-format:
 # default is true, you could omit this line if you would like to disable it.
 enabled: true 
 options:
   # the default is json, 
   default: json
   # the supported format, if you not set the support format, it only work for default format you setup
   formats: json, csv  
```

so if you would like to support default CSV,  you could do like this way:
```yaml
response-format:
 options:
   default: csv

# becase the sample does not provide formats, so even you given `/work.json`, it  will only response json format result.
```

Or setup the `format` to declare what response format supported:

so if you would like to support default CSV,  you could do like this way:
```yaml
response-format:
 options:
   formats: json, csv
```

**Comment by oscar60310** [comment]
I have enabled both json and csv foramt, here is my config:
```yaml
response-format:
  # default is true, you could omit this line if you would like to disable it.
  enabled: true
  options:
    # the default is json,
    default: json
    # the supported format, if you did not set the support format, it only works for the default format you set up
    formats:
      - json
      - csv
```
The serve always returns CSV format when I change the order of `formats` property:
```yaml
response-format:
  # default is true, you could omit this line if you would like to disable it.
  enabled: true
  options:
    # the default is json,
    default: json
    # the supported format, if you did not set the support format, it only works for the default format you set up
    formats:
      - csv
      - json
```

Here is the `accept` header sent by the browser:
```
text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
```
We treat accept header and the extension name as the same weight, so the server always uses the first format.
https://github.com/Canner/vulcan/blob/develop/packages/serve/src/lib/middleware/response-format/helpers.ts#L18-L19
