### ISSUE TITLE
Data source profiles

### ISSUE THREAD

**Issue by oscar60310** [Canner/vulcan-sql#71]
## **What’s the problem you're trying to solve**
We need to load data source connection information to execute queries, e.g. host, port, dbname, dbuser, dbpassword ...  for Postgres.

## **Describe the solution you’d like**
1. Users can set `profiles` property in their project config file (vulcan.yaml), it contains all the profiles' paths, in order of priority, from top to bottom.
    ```yaml
    profiles:
      - some/path/to/profiles.yaml
      - another/path/to/profiles.yaml
    ```

2. Two default paths will append at the end automatically: `profiles.yaml` and `~/.vulcan/profiles.yaml`. For example:
    ```yaml
    profiles:
      - some/path/to/profiles.yaml
      - another/path/to/profiles.yaml
    ```
    We'll try to find profiles from `some/path/to/profiles.yaml` first, then `another/path/to/profiles.yaml`, `profiles.yaml`, and  `~/.vulcan/profiles.yaml`

3. Profiles are duplicated by their names.
4. This is an example of a profile file:
    ```yaml
    - name: pg-admin # required. the name of this profile
       type: pg # required. which driver we should use
       connection: # required. connection info, which depends on drivers
          host: example.com
          username: vulcan
          password: xxxx
    - name: duck
      type: duck
      connection:
          path: ./path/to/db
    ```
5. We'll need to set which profile we want to use at endpoints' schemas:
    ```yaml
    urlPath: /users
    profile: pg-admin
    ```

## **Additional context**
1. Switching profiles by environment (production, dev ...) might be implemented in the future.
2. We'll implement authorization feature soon, we'll set multiple profiles for one endpoint at that time.
